CREATE TABLE IF NOT EXISTS users (
  id          VARCHAR(36)  PRIMARY KEY,
  username    VARCHAR(20)  NOT NULL UNIQUE,
  password    VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exams (
  id        VARCHAR(36)  PRIMARY KEY,
  user_id   VARCHAR(36)  NOT NULL,
  subject   VARCHAR(100) NOT NULL,
  grade     TINYINT      NOT NULL,
  ects      TINYINT      NOT NULL,
  added_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
